// SJSU CS 218 Fall 2021 TEAM3

package com.cloud.project.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "items")
public class Items {

	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String itemId;

	@DynamoDBAttribute
	private String name;

	@DynamoDBAttribute
	private String description;

	@DynamoDBAttribute
	private int baseAmount;

	@DynamoDBAttribute
	private int highestBid;

	@DynamoDBAttribute
	private String highestBidder;

	@DynamoDBAttribute
	private String s3ImageLink;

	@DynamoDBAttribute
	private String creationTime;
	
	@DynamoDBAttribute
	private String expiryDate;
	
	@DynamoDBAttribute
	private boolean expired;

	public String getItemId() {
		return itemId;
	}

	public void setItemId(String itemId) {
		this.itemId = itemId;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getHighestBidder() {
		return highestBidder;
	}

	public void setHighestBidder(String highestBidder) {
		this.highestBidder = highestBidder;
	}

	public String getCreationTime() {
		return creationTime;
	}

	public void setCreationTime(String creationTime) {
		this.creationTime = creationTime;
	}

	public String getS3ImageLink() {
		return s3ImageLink;
	}

	public void setS3ImageLink(String s3ImageLink) {
		this.s3ImageLink = s3ImageLink;
	}

	public int getBaseAmount() {
		return baseAmount;
	}

	public void setBaseAmount(int baseAmount) {
		this.baseAmount = baseAmount;
	}

	public int getHighestBid() {
		return highestBid;
	}

	public void setHighestBid(int highestBid) {
		this.highestBid = highestBid;
	}

	public String getExpiryDate() {
		return expiryDate;
	}

	public void setExpiryDate(String expiryDate) {
		this.expiryDate = expiryDate;
	}

	public boolean isExpired() {
		return expired;
	}

	public void setExpired(boolean expired) {
		this.expired = expired;
	}

}
