// SJSU CS 218 Fall 2021 TEAM3

package com.cloud.project.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "user")
public class User {

	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String userId;

	@DynamoDBAttribute
	private String firstName;

	@DynamoDBAttribute
	private String lastName;

	@DynamoDBIndexHashKey(attributeName = "email", globalSecondaryIndexName = "email-index")
	private String email;

	@DynamoDBAttribute
	private String password;

	@DynamoDBAttribute
	private String bidItems;

	@DynamoDBAttribute
	private String bidItemAmount;

	@DynamoDBAttribute
	private String bidsWon;

	@DynamoDBAttribute
	private String sellItems;

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getBidItems() {
		return bidItems;
	}

	public void setBidItems(String bidItems) {
		this.bidItems = bidItems;
	}

	public String getSellItems() {
		return sellItems;
	}

	public void setSellItems(String sellItems) {
		this.sellItems = sellItems;
	}

	public String getBidItemAmount() {
		return bidItemAmount;
	}

	public void setBidItemAmount(String bidItemAmount) {
		this.bidItemAmount = bidItemAmount;
	}

	public String getBidsWon() {
		return bidsWon;
	}

	public void setBidsWon(String bidsWon) {
		this.bidsWon = bidsWon;
	}

}
